/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AImage: typeof import('ant-design-vue/es')['Image']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    ImageViewer: typeof import('./src/components/ImageViewer.vue')['default']
    PhotoViewer: typeof import('./src/components/PhotoViewer.vue')['default']
    ZoomableImage: typeof import('./src/components/ZoomableImage.vue')['default']
  }
}
