/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    HtmlToCanvas: typeof import('./src/components/HtmlToCanvas.vue')['default']
    ImageViewer: typeof import('./src/components/ImageViewer.vue')['default']
  }
}
